excluded:
  - ${PWD}/Pods
  - ${PWD}/Example/Pods

analyzer_rules:
  - typesafe_array_init
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - closure_end_indentation
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - no_magic_numbers
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - unused_closure_parameter
  - large_tuple
  - multiple_closures_with_trailing_closure
  - implicit_return
  - vertical_whitespace_between_cases

empty_count: warning
force_cast: warning

trailing_comma:
  mandatory_comma: true

identifier_name:
  excluded:
    - i
    - n
    - id
    - on
    - x
    - y
    - z
    - dx
    - dy
    - dz
    - to
    - at

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

nesting:
  type_level:
    warning: 2

custom_rules:
  already_true:
    regex: "== true"
    message: "Don't compare to true, just use the bool value."
  already_bool:
    regex: "== false"
    message: "Don't compare to false, just use !value."
  auto_generated_leftovers:
    regex: 'func [^\n]*\{\n(\s*super\.[^\n]*\n(\s*\/\/[^\n]*\n)*|(\s*\/\/[^\n]*\n)+)\s*\}'
    message: "Delete auto-generated functions that you don't use"
#  commented_code:
#    regex: '(?<!:|\/)\/\/\h*[a-z.](?!wiftlint)'
#    message: "Comment starting with lowercase letter - did you forget to delete old code?"
#  multiline_commented_code:
#    regex: '^\s*[a-z]'
#    match_kinds: comment
#    message: "Comment starting with lowercase letter - did you forget to delete old code?"
#  non_localized_word:
#    regex: '(?<!NSLocalizedString\()"[[:upper:]][[:lower:]]+"'
#    message: "Wrap string in NSLocalizedString()"
#  non_localized_sentence:
#    regex: '(?<!NSLocalizedString\(|fatalError\(|\S)"[^"]+ [^"]*"'
#    message: "Wrap string in NSLocalizedString()"
#  non_localized_multiline:
#    regex: '(?<!NSLocalizedString\()""".*?"""'
#    message: "Wrap string in NSLocalizedString()"
